name: welcoke_to_github

on:
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello world
        run: echo hello world

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: building done here
        run: echo building

    
